name: Node.js CI

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with: 
        repository: ${{ github.repository }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn install
    - run: yarn test
    - name: "Publish test results"
      uses: peaceiris/actions-gh-pages@v3.7.3
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: '.'
        keep_files: true
        user_name: github-actions[bot]
        user_email: github-actions[bot]@users.noreply.github.com
    env: 
      NASA_API_KEY: ${{secrets.NASA_API_KEY}}
